# Linux node_exporter targets.
#
# Example:
# - targets:
#     - 192.168.1.10:9100
#   labels:
#     hostname: ubuntu-server-01
#     role: server
#     site: home
#     os: linux

- targets:
    - "10.10.10.41:9100"
  labels:
    hostname: "bl-dock-01"
    role: "server"
    site: "home"
    os: "linux"

- targets:
    - "10.10.10.28:9100"
  labels:
    hostname: "proxmox-10-10-10-28"
    role: "virtualization"
    site: "home"
    os: "proxmox"

- targets:
    - "10.10.10.29:9100"
  labels:
    hostname: "proxmox-10-10-10-29"
    role: "virtualization"
    site: "home"
    os: "proxmox"
